# Site settings
title: Samuel Zapolsky
email: samzapo@gmail.com
url: https://samzapo.github.io
description: "The research and coding homepage for Samuel Zapolsky.  Contains blog posts for recent successful research endeavors and up-to-date news about ongoing research."
skills: "Getting robots to run without breaking themselves | More difficult than it sounds"
meta_author: Zapolsky Samuel
paginate_path: "blog/page:num/"
permalink: blog/:title/
gems: [jekyll-paginate]

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 565656
  primary-rgb: "86,86,86"
  secondary: 303030
  secondary-dark: E87600  

# Footer settings
footer:
  copyright: Samuel Zapolsky
  location: Washington, DC
  social: On the Interwebs
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/BoopBeepRobot
  - title: instagram
    url: https://www.instagram.com/the_robot_overlord/
  - title: github
    url: http://github.com/samzapo

# Postal address (add as many lines as necessary)
address:
  - line: 800 22nd St NW
  - line: Washington, DC 20052

# Credits content
credits: 'Samuel Zapolsky is a Ph.D. Student working in the Positronics Lab @ GWU, for more info on our research visit <a href="http://positronicslab.github.io/">Positronics Lab Homepage</a>'

# Build settings
markdown: kramdown
#permalink: pretty
