# Site settings
title: Guo Xiaoyuan
email: xiaoyuanguo.ucas@gmail.com
url: https://xiaoyuanguo.github.io
description: "The research and coding homepage for Guo Xiaoyuan.  Contains blog posts for recent successful research endeavors and up-to-date news about ongoing research."
skills: "Getting robots to run without breaking themselves | More difficult than it sounds"
meta_author: Xiaoyuan Guo
paginate_path: "blog/page:num/"
permalink: blog/:title/
gems: [jekyll-paginate]

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 565656
  primary-rgb: "86,86,86"
  secondary: 303030
  secondary-dark: E87600  

# Footer settings
footer:
  copyright: Guo Xiaoyuan
  location: Beijing, China
  social: On the Interwebs
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: QQ
    url:
  - title: Weixin
    url:
  - title: github
    url: http://github.com/xiaoyuanguo

# Postal address (add as many lines as necessary)
address:
  - line: University of Chinese Academy of Sciences
  - line: Beijing, China

# Credits content
credits: 'Guo Xiaoyuan is a M.S. Student at UCAS, for more info on our research visit <a href="http://guoxiaoyuan.github.io/">Vision Lab Homepage</a>'

# Build settings
markdown: kramdown
#permalink: pretty
